# Kaggle dataset
kaggle_dataset: tsiaras/uk-road-safety-accidents-and-vehicles
zipped_dataset: uk-road-safety-accidents-and-vehicles.zip

# Specify database details
db_host : localhost
db_port : 5432
db_user: user_with_create_db_rights
db_pass: password
existing_db_name: existing_db_name

# Database to be created and then utilized
new_db_name : stuart

# Specify whether to take only the last 100 accidents or the whole set
is_take_only_100_recent_accidents: True

# DB schame
db_schema: db_schema.sql
fact_table: recent_accidents

# Input files
accidents_csv : Accident_Information.csv
vehicles_csv : Vehicle_Information.csv

# List of columns of interest from the accidents data
list_of_acc_columns : 
- Accident_Index
- Accident_Severity
- Date
- Day_of_Week
- Time

# List of columns of interest from the vehicles data
list_of_veh_columns : 
- Accident_Index
- Age_Band_of_Driver
- Age_of_Vehicle
- Driver_Home_Area_Type
- Journey_Purpose_of_Driver

# We have the following dimention tables, thus we look them up in order to set the foreign keys in the fact table.
dimension_lookups :
- accident_severity
- age_band_of_driver
- driver_home_area_type
- journey_purpose_of_driver